/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 17.06.2026 19:12:42

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 6
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 12
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 5936;
#else
constexpr int kTensorArenaSize = 4912;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,650 } };
const TfArray<1, float> quant0_scale = { 1, { 0.04915672168135643, } };
const TfArray<1, int> quant0_zero = { 1, { -3 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 50, 13, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 50, 1, 32, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 25, 32, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 25, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[4] = { 1, 1, 13, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[4] = { 1, 13, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data7[2] = { -1, 56, };
const TfArray<1, int> tensor_dimension7 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[6] = { -68, 1751, 1399, -1239, -1498, -738, };
const TfArray<1, int> tensor_dimension8 = { 1, { 6 } };
const TfArray<1, float> quant8_scale = { 1, { 0.00042301107896491885, } };
const TfArray<1, int> quant8_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[6*56] = { 
  -54, 22, -59, -38, -6, 4, -1, 12, 17, 28, -59, -19, -16, 17, -2, 16, 36, 30, -62, -33, -7, 18, 5, 18, 31, 47, -48, -20, -1, 11, -24, 21, 19, 43, -29, -12, -15, 4, 6, 13, 25, 25, -17, -29, 11, -18, -3, 42, 35, 21, -30, -77, 5, -42, -6, 13, 
  -4, -56, -36, -38, 26, 32, -5, -59, -26, -65, -55, -19, 3, 37, -27, -76, -43, -37, -59, -43, -7, 36, 11, -93, -57, -57, -39, -29, 18, 32, 11, -66, -74, -6, 5, 3, -4, 25, 11, -71, -31, -36, 12, 3, 23, 16, 12, -26, -6, -27, 9, 37, 10, 30, -21, -21, 
  -34, -27, 17, -2, 38, -26, -8, 21, -9, -8, 19, 16, 24, -4, -14, 4, -35, 22, 19, -13, 25, -9, -35, 5, -26, 22, -2, -13, 32, -18, -77, 4, -33, 22, 17, -5, 17, -17, -53, -9, -15, 10, 29, -14, 39, -11, -55, 26, 12, -23, 3, -21, 37, -1, -17, 4, 
  -56, 27, 9, 40, -31, -79, 18, 23, 20, 25, 11, 40, -29, -68, -14, 18, 27, 37, 18, 14, -28, -62, -6, 20, 24, 47, -9, 16, -25, -49, -15, 11, 19, 31, -20, 19, -34, -40, 6, -6, 20, 28, -11, -6, -1, -37, 5, 31, 27, 15, -35, -34, 5, -31, -12, -3, 
  5, -69, 24, -110, 24, -35, 51, -18, 31, -59, 17, -19, 18, -63, 38, -34, 37, -78, 18, -18, 25, -17, 50, -32, 25, -127, 17, 0, 33, -31, 38, -12, 21, -73, 13, 18, -9, -42, 43, -43, 13, -62, 21, 7, -9, -16, 38, 9, 8, -58, 9, 13, -22, -5, 12, 27, 
  -13, -80, 12, 49, -34, 13, 7, 49, 3, -63, 21, 40, -52, 24, -10, 30, -12, -55, 21, 23, -70, 32, 11, 13, -16, -58, 2, 36, -47, 29, -2, 16, -52, -12, 3, 24, -12, 17, 2, -35, -48, -1, -26, -5, 11, 9, -4, -16, -25, -20, -28, 3, -34, 24, -26, -15, 
};
const TfArray<2, int> tensor_dimension9 = { 2, { 6,56 } };
const TfArray<1, float> quant9_scale = { 1, { 0.0094924904406070709, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { -1197, 962, 215, 332, 218, -848, -937, 559, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 0.00024639154435135424, 0.00040480916504748166, 0.00031753579969517887, 0.00027992684044875205, 0.00021333807671908289, 0.00018682483641896397, 0.00026706690550781786, 0.0003162797074764967, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*16] = { 
  /* [0][0][][] */ 29,9,-9,-127,78,54,-90,-73,-69,-98,-24,-24,-28,-82,-4,16, 12,-66,1,-84,9,28,-65,9,-34,-48,-27,-25,-57,55,37,-1, 47,-31,-9,-8,50,49,-44,2,-17,-53,6,15,-6,-2,13,-31, 
  /* [1][0][][] */ 29,-6,-37,68,-88,-63,-70,-4,15,-69,-91,-57,49,-55,-80,14, -3,10,-26,47,-127,-62,-13,18,-7,-97,-27,-10,9,-48,-100,-27, -26,60,-14,45,-87,-72,13,10,-10,-21,-28,-17,30,-83,-24,-32, 
  /* [2][0][][] */ -59,-29,-13,38,-38,2,-100,42,29,-123,-14,24,0,8,-78,-38, -65,14,17,14,-28,18,-113,50,9,-95,-37,43,-17,-16,-127,13, 2,-2,11,51,-24,-28,-38,60,13,-37,6,78,-80,-46,-31,49, 
  /* [3][0][][] */ -44,36,-34,97,-93,-6,-72,58,-11,-102,20,30,-8,21,-127,-106, 3,7,-9,67,-30,31,-86,14,-12,-78,62,65,-11,-14,-43,-95, -9,33,9,90,-7,27,-42,52,-26,-55,79,73,-51,-22,-2,-72, 
  /* [4][0][][] */ -38,-39,21,-41,-4,-89,-13,-52,73,-8,-91,-90,-44,-19,-19,46, 40,-27,63,-6,-9,-98,12,-48,5,-4,-102,-92,-69,-127,2,61, -17,-52,35,-76,-10,-99,-9,-30,55,-27,-115,-81,-48,-114,-15,41, 
  /* [5][0][][] */ -55,7,-69,-33,-78,-92,95,-97,-9,122,-15,-127,-11,93,42,-64, -90,-8,-45,-82,-78,-1,26,-63,14,52,-77,-20,-3,69,27,-30, -68,3,-23,-80,-31,-8,104,-73,-36,65,15,81,-55,33,32,-41, 
  /* [6][0][][] */ 75,25,-65,-47,23,65,28,53,-105,16,-22,23,-102,-77,7,-13, 16,37,-127,46,-21,20,7,4,-82,-5,-83,24,-80,-100,-5,-79, -105,48,-38,8,24,46,-117,51,-41,11,-126,24,-30,-7,-62,-59, 
  /* [7][0][][] */ -45,17,3,41,43,4,-91,-48,6,-95,-30,-60,48,-25,-1,-59, -62,-32,21,-11,22,48,-73,13,23,-77,43,40,-17,-74,7,-69, -22,-71,39,47,26,31,-17,-127,-9,-33,66,46,45,-55,-10,-35, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,16 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0050127366557717323, 0.0082356790080666542, 0.006460137665271759, 0.0056949988938868046, 0.0043402770534157753, 0.003800875972956419, 0.0054333684965968132, 0.0064345831051468849, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data12[16] = { 882, -706, -1220, -782, -1472, -45, 1832, 54, -2358, 2431, -651, -150, 4292, 560, 1029, -1375, };
const TfArray<1, int> tensor_dimension12 = { 1, { 16 } };
const TfArray<16, float> quant12_scale = { 16, { 0.00022107471886556596, 0.00016688350297044963, 0.00015643857477698475, 0.00025576102780178189, 0.00020659278379753232, 0.00019592861644923687, 0.00022058507602196187, 0.00022868710220791399, 0.00016813233378343284, 0.00021347177971620113, 0.00018652627477422357, 0.00024270876019727439, 0.00019882737251464278, 0.00026420463109388947, 0.00022979997447691858, 0.00020252291869837791, } };
const TfArray<16, int> quant12_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&quant12_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data13[16*1*3*32] = { 
  /* [0][0][][] */ 39,-16,-4,36,-55,-71,5,45,-51,-13,-38,-53,-67,10,8,-42,32,15,13,54,-63,-59,-21,-8,-60,-43,76,-49,-47,-4,15,-4, -7,-37,-24,40,-59,-89,6,-27,-6,9,-64,-63,-21,43,39,-27,24,-7,-15,-13,-59,-34,-14,3,-43,-15,-8,-20,-39,22,-39,9, 8,-50,-31,4,-85,-127,21,-69,-14,-60,-30,-85,-50,-57,-15,-26,62,-111,-29,38,-18,-72,-12,79,-71,1,-15,1,14,30,-21,-16, 
  /* [1][0][][] */ -73,48,-54,4,65,-43,3,-67,18,-40,-73,10,40,-34,-76,1,2,-64,-127,-97,30,-44,-68,-11,-27,-58,-37,-27,-71,-24,-39,-30, -31,55,13,76,42,-30,-24,-87,-9,-54,-93,-6,-2,2,-76,-19,-8,-36,26,18,-13,68,-6,-50,-23,27,-4,25,-5,45,-50,-14, -29,23,74,-16,40,-3,-30,-34,7,-75,-44,-27,-90,-28,33,124,-10,67,88,-12,14,59,5,-66,13,-30,-46,-1,-46,36,-30,-48, 
  /* [2][0][][] */ -19,42,-11,-61,-5,11,0,27,-34,-19,-53,80,15,8,-2,-32,-65,-7,33,-67,-73,40,117,-59,84,48,-64,49,-59,-53,5,8, 28,-11,5,-55,45,-24,-44,25,-54,-43,-14,-61,9,12,60,-51,-37,10,-7,-29,-127,5,92,-10,29,32,64,66,54,-44,-30,-56, 31,-48,44,-7,5,-71,8,6,-13,-22,-14,-103,41,29,14,-9,15,23,-31,-55,-98,11,124,-25,40,-33,46,37,54,-31,103,30, 
  /* [3][0][][] */ -12,-59,-6,-60,-70,-102,-1,16,2,-50,-15,-48,-6,-78,-54,-67,-9,1,-27,-53,33,-12,39,-20,3,-34,-32,4,-25,-127,-6,3, -31,-3,5,-114,-57,-81,17,42,1,-69,-39,-45,-68,-71,-26,38,-11,7,40,-16,0,-7,-35,12,-41,-89,-90,23,-20,-23,-19,-20, -61,50,-4,-74,56,-13,-3,-36,-37,-21,-41,-18,-12,-32,-85,63,-23,-66,40,-49,-43,-22,-23,-31,-52,5,11,53,-54,69,-8,-48, 
  /* [4][0][][] */ 60,-15,-74,-18,92,-80,-38,67,-104,-15,-25,-51,-29,17,51,-50,-37,62,13,9,3,-26,-48,-43,-36,-37,27,-98,-56,9,8,-39, 3,37,-74,4,27,-39,-74,65,-76,44,-2,-45,7,-5,18,-11,-52,-2,22,13,27,-43,-33,-79,-33,6,19,-75,-30,-9,-44,0, 17,22,-54,-26,43,-47,-76,17,-127,-14,7,-52,2,36,11,-13,15,40,-11,6,50,-70,-38,-87,-26,8,31,-51,-58,-8,-84,-15, 
  /* [5][0][][] */ -7,46,-51,-20,23,-42,-111,53,-127,56,-15,-31,-5,15,13,-45,-102,92,0,49,64,-21,-13,-58,-47,7,26,-38,-13,1,-21,-90, -42,24,-111,0,15,-21,-116,15,-34,5,-75,61,-67,-35,7,-39,-16,3,-52,7,-10,-37,10,-12,42,12,-100,-49,-71,-20,-99,-124, -28,42,-103,64,27,33,-92,-41,-73,-8,-6,17,3,62,15,-42,57,-11,-57,21,36,-52,-55,-39,27,37,-88,-95,-33,2,-75,-51, 
  /* [6][0][][] */ 61,-60,8,22,-42,-4,5,-12,12,49,79,-9,-32,-34,-20,-19,12,-71,-22,57,-30,38,-127,-21,-34,37,-23,-8,-65,10,-71,23, 53,-79,-23,8,-36,42,-49,4,-62,-25,57,-9,-54,-36,-64,19,-5,-99,-83,12,-56,22,-32,-57,-38,20,2,-16,-22,15,-32,70, -15,-1,29,-14,22,16,-93,12,-59,-75,-44,-43,-93,-74,-72,32,-79,-91,-106,18,-28,49,-37,-63,-62,-82,83,12,-35,28,-3,-77, 
  /* [7][0][][] */ -65,43,22,-103,-1,12,-6,-68,23,-10,-24,-23,-51,29,-30,25,-8,-37,70,-35,33,-29,29,41,-12,4,-37,26,-52,-13,-39,-23, -77,54,-25,-33,9,20,-35,-24,-27,-66,-62,12,-61,-62,-67,23,-19,-23,42,-33,20,-23,34,-19,-50,22,-52,27,-69,23,-97,-119, -84,-2,-43,27,21,33,-13,-59,-8,-81,-56,32,6,-60,-101,50,32,-120,-50,-92,4,-29,30,-49,10,58,-52,-56,-8,23,-127,-87, 
  /* [8][0][][] */ 21,-35,53,-16,-59,-41,28,11,-6,-9,-24,23,50,-44,-26,4,-4,17,54,-95,-41,61,-2,-26,35,-30,45,117,-18,-127,60,83, 34,8,16,-12,-15,-4,-21,9,-45,-31,-23,-17,-11,8,47,-31,13,-19,35,-74,-37,15,74,0,35,-3,61,6,53,-102,-5,28, 24,-5,39,7,-9,-7,16,-32,-40,-27,-5,-4,44,-18,4,7,39,-27,-62,-77,-39,60,80,-4,26,-23,18,44,73,-104,-24,39, 
  /* [9][0][][] */ 46,-40,7,15,-65,34,-101,29,-85,-23,84,3,-36,-26,-57,11,37,-49,-59,39,-26,24,-68,-15,-10,48,-16,-29,-59,35,-42,30, 15,5,-12,8,16,-13,-84,-13,-93,-39,71,-24,-77,-41,-73,-17,-46,-33,-93,22,-8,-27,-65,-21,-46,18,-32,-39,-66,-2,-71,-8, -14,49,-30,4,32,29,-127,37,-85,-3,11,-46,-83,-37,-62,24,-97,-63,-82,5,14,-23,-23,-44,-63,-40,2,-50,-33,-10,13,-103, 
  /* [10][0][][] */ -14,100,-97,5,38,-8,-64,-12,-74,-90,-77,-26,19,-13,-95,-1,-10,-22,-61,25,5,-30,65,-68,60,87,-60,-71,-34,21,19,-84, -13,-80,-92,10,-44,-19,-31,-77,30,-33,-88,19,35,17,-30,-111,-27,-38,-68,-10,-7,-73,-33,-12,6,-22,-32,-32,31,50,-15,-69, -27,-58,-40,39,-81,-89,-45,-5,-31,-45,-53,-66,20,95,27,-103,-20,-8,-24,31,-92,-127,-51,-77,36,4,33,-21,-32,69,-17,0, 
  /* [11][0][][] */ -1,127,2,-6,-13,-23,-83,8,-39,-26,-33,-18,-46,-45,-62,-2,-84,-15,11,14,9,-73,65,-35,-51,38,-26,-58,-68,-72,-28,-93, -95,-31,-20,-46,-3,-17,-74,-3,-13,-62,-43,51,12,-37,-51,-21,-27,-34,-21,38,38,12,-20,16,74,-12,-50,-41,-9,-5,-40,-122, -56,-122,-72,16,-49,-27,-66,11,8,-44,-46,12,35,46,-9,-19,-22,-81,-49,10,-38,-10,-79,-29,28,21,-14,-11,-26,27,-24,1, 
  /* [12][0][][] */ -24,-32,44,6,-61,-56,42,-30,-4,-54,-25,-83,-126,-61,-57,-32,24,-12,-25,-21,6,-54,-49,35,-49,-86,-45,22,-39,-27,22,-11, 16,-66,7,0,-57,-35,-8,-27,-2,-68,-6,-34,-127,-124,-39,27,-1,-24,-56,-49,-7,18,-44,10,-1,6,2,-4,-64,-83,22,3, 1,-24,69,27,-79,0,19,-43,8,-60,-56,-59,-114,-104,-48,45,25,-54,-73,12,54,25,31,-17,-31,-24,-31,19,-83,3,-16,3, 
  /* [13][0][][] */ -60,-22,-62,-127,-61,-65,6,-75,14,11,-36,-32,-22,-81,-5,-49,-59,8,31,-44,15,-103,-18,25,-43,-59,-52,-60,18,-97,-2,-4, -73,-16,-38,-92,-78,-31,12,-54,-3,4,-5,-44,20,-89,-11,-8,-17,43,28,-33,16,-46,28,2,-7,-86,-47,-39,23,-69,8,27, -37,20,-62,-9,-111,-6,-3,-98,-1,39,-9,-5,20,-26,-35,-49,-32,39,38,6,2,-42,-26,-7,-73,-58,-11,-21,-23,-13,4,13, 
  /* [14][0][][] */ 32,-38,1,19,-38,53,-45,9,-50,9,82,-12,-59,-13,40,24,14,10,31,61,-19,14,-47,-73,10,25,17,3,-57,45,-48,0, 44,-35,-4,10,-10,9,-47,32,-127,9,-1,-57,-28,-27,-14,20,6,12,-18,-13,-24,33,-40,-92,-35,8,56,14,-25,-1,-37,-20, -54,-14,-20,-10,12,10,-51,6,-82,41,-30,-93,26,26,-38,15,-7,-4,-28,0,-8,-9,-47,-13,-39,-57,40,-38,24,-14,31,-6, 
  /* [15][0][][] */ -65,-17,9,-127,16,-5,-37,-28,-30,-36,39,-62,-46,-1,4,4,-57,-29,15,-19,-86,-56,1,52,-15,-20,26,35,45,-36,-27,-17, -15,-49,30,-56,17,-24,-90,-8,-58,-70,30,-78,-8,0,-4,-12,-61,-27,-52,-3,-58,0,34,66,-38,-58,37,24,61,-27,-25,-66, 24,-37,53,-27,-29,-30,-44,-37,-56,-92,59,-45,-50,36,27,-10,-24,-19,-1,44,-86,-16,-26,56,-26,-72,43,25,37,-14,43,-44, 
};
const TfArray<4, int> tensor_dimension13 = { 4, { 16,1,3,32 } };
const TfArray<16, float> quant13_scale = { 16, { 0.0064566419459879398, 0.0048739495687186718, 0.004568898119032383, 0.0074696801602840424, 0.0060336869210004807, 0.0057222321629524231, 0.0064423414878547192, 0.0066789668053388596, 0.0049104224890470505, 0.0062345927581191063, 0.0054476303048431873, 0.0070884791202843189, 0.0058068926446139812, 0.0077162808738648891, 0.0067114690318703651, 0.0059148236177861691, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data14[32] = { -3557, -7165, -1854, -3484, -5921, -3150, 748, -3048, 421, -2600, -4257, -2985, -1980, -3967, -4134, -3740, -1886, -3516, -2538, -6316, -3165, -4281, -1265, -2838, -3294, -4782, -2439, -2048, -2667, -5878, -1121, -1512, };
const TfArray<1, int> tensor_dimension14 = { 1, { 32 } };
const TfArray<32, float> quant14_scale = { 32, { 0.00021441606804728508, 0.00019050443370360881, 0.00024323850811924785, 0.00018443123553879559, 0.00018192344577983022, 0.00015453738160431385, 0.00033737692865543067, 0.00024663115618750453, 0.00026037308271043003, 0.00027694401796907187, 0.00027741451049223542, 0.00022853155678603798, 0.00032829892006702721, 0.00022622940014116466, 0.00021315802587196231, 0.00023048973525874317, 0.00020562285499181598, 0.00024155221763066947, 0.00041080696973949671, 0.00018394249491393566, 0.0001867343089543283, 0.00018621949129737914, 0.00041979103116318583, 0.00020811746071558446, 0.00022903997160028666, 0.00017269981617573649, 0.00023721565958112478, 0.00029170812922529876, 0.00032557817758060992, 0.00017325632506981492, 0.00033536329283379018, 0.00037486513610929251, } };
const TfArray<32, int> quant14_zero = { 32, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant14 = { (TfLiteFloatArray*)&quant14_scale, (TfLiteIntArray*)&quant14_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data15[32*1*3*13] = { 
  /* [0][0][][] */ 60,-27,0,99,109,49,32,70,28,-5,48,86,-7, -33,52,32,74,39,33,47,76,82,43,42,-3,-28, -18,-12,-3,31,-127,1,37,62,13,24,-20,-99,8, 
  /* [1][0][][] */ -33,-50,-111,19,-7,83,31,-86,-41,8,127,-69,-12, 15,60,-77,-31,-21,31,18,-21,-61,-3,-37,86,-95, 63,99,-53,-91,-97,1,-23,57,-18,-12,-55,33,18, 
  /* [2][0][][] */ 9,-43,56,10,51,67,28,-21,-29,-6,-24,-67,5, -25,-38,-9,-99,-112,-127,-33,51,19,18,-2,6,35, 89,-9,-20,-22,77,112,74,62,6,-15,18,1,-25, 
  /* [3][0][][] */ -60,98,127,16,63,-26,27,21,30,28,-10,119,-30, -60,81,124,-48,57,-15,29,18,25,62,14,2,22, -52,73,74,27,1,-54,88,26,31,9,-5,-48,44, 
  /* [4][0][][] */ 119,-102,-28,108,21,77,-94,-29,-109,-44,6,-15,-37, 52,-10,4,-27,-2,-15,-60,-47,-84,-81,-28,68,-14, 20,55,-63,-77,-43,-65,-127,-65,9,-38,78,-67,49, 
  /* [5][0][][] */ 54,101,-2,22,-124,-24,122,1,15,8,-43,-69,-10, 51,-73,30,-127,-31,-27,108,-82,0,17,-1,-69,20, -36,14,-59,17,-127,-21,77,-72,-83,-55,-82,-88,38, 
  /* [6][0][][] */ -34,30,-8,-22,-17,-23,-7,20,27,25,-10,-14,-5, -127,-66,-37,-2,16,40,40,11,-20,6,-11,19,-20, -81,-37,13,13,-25,-42,-70,-26,9,0,34,28,6, 
  /* [7][0][][] */ 49,-17,-9,127,60,-46,20,-5,7,-6,-15,-93,-31, 87,-15,5,25,32,-13,-1,-1,-7,10,-29,-36,11, -1,-44,-23,-33,-64,-11,-56,-43,49,1,-48,-25,28, 
  /* [8][0][][] */ -109,20,-11,-79,18,-56,-23,6,24,2,-7,-44,-20, -90,-59,-4,12,-49,-6,16,13,-12,37,-53,9,12, -127,-112,-60,20,-24,2,21,10,-30,26,31,-53,-21, 
  /* [9][0][][] */ -127,16,-20,-2,-10,31,-38,-31,-21,22,1,18,-28, -81,0,3,8,30,18,-37,-67,-24,11,-1,18,-36, -69,59,-46,24,61,16,-26,-46,-7,30,40,28,-37, 
  /* [10][0][][] */ 32,-43,30,-127,-56,58,49,-22,-10,-72,4,-16,-14, 29,-84,56,-42,16,31,34,-46,15,-63,5,-29,-12, 8,-16,13,35,108,16,23,-20,23,25,11,-6,8, 
  /* [11][0][][] */ -75,40,-17,-86,-57,16,23,-11,-39,-41,-45,6,-1, -57,127,36,-74,-81,-70,-17,21,58,30,29,-38,-30, -61,55,31,12,-20,-71,-47,-7,58,43,-13,-24,-7, 
  /* [12][0][][] */ -75,87,13,-42,-51,-9,-10,3,21,32,10,-20,-14, -25,60,-2,21,87,-25,-1,3,-26,-26,-1,-1,-11, -127,12,-8,33,12,10,-21,-29,18,15,18,9,12, 
  /* [13][0][][] */ -5,77,30,64,63,-37,-81,-43,-17,5,7,-54,6, 38,72,68,58,68,16,62,-13,-25,16,-9,8,32, -47,43,-49,52,127,92,-9,-26,18,44,47,9,-33, 
  /* [14][0][][] */ 127,-43,6,21,80,-46,-39,0,-35,-12,15,42,16, 106,-107,-20,87,56,12,-24,-9,-7,21,-39,-25,-11, -31,-49,-4,40,44,4,-48,-5,39,23,36,98,6, 
  /* [15][0][][] */ -66,-55,66,-34,7,-11,1,38,54,1,-52,-12,6, 14,11,74,-32,-50,34,-13,23,-4,-20,-33,-38,-53, 79,72,10,20,-127,-6,43,28,-22,-51,4,9,18, 
  /* [16][0][][] */ -39,96,71,28,-24,64,40,104,91,7,-31,53,25, -41,22,9,4,-43,14,-22,10,-4,-6,63,24,26, -123,-59,13,-34,-26,1,31,103,127,-21,25,26,4, 
  /* [17][0][][] */ -25,-101,-9,127,57,-6,0,-35,-20,16,5,-30,-12, -65,-47,2,120,53,-17,-38,-39,8,3,-31,20,-10, -34,-2,-27,42,18,19,-98,8,26,-4,-11,-32,14, 
  /* [18][0][][] */ -127,-62,-35,3,64,1,-5,10,5,9,-2,-24,21, 14,-35,-7,48,-3,-8,-3,-14,-19,3,1,15,-30, 57,11,-2,30,-17,4,4,12,-6,-18,19,18,-26, 
  /* [19][0][][] */ 55,31,85,16,123,33,13,-8,28,56,36,37,-37, 34,18,42,16,78,-52,61,21,4,75,-127,41,-22, 28,42,-4,24,-31,-5,0,50,-79,50,-86,47,-40, 
  /* [20][0][][] */ -37,-55,-60,-42,69,-57,-11,-46,56,-35,85,-114,17, -67,-27,-70,-83,23,-28,3,-99,82,-3,46,-80,2, -127,7,-118,-115,-33,-64,18,-14,12,-36,121,-52,23, 
  /* [21][0][][] */ -65,68,57,51,85,15,31,45,127,55,66,10,10, -68,79,17,17,-125,-71,9,88,51,1,-67,-126,45, 29,-59,-77,-82,-67,-13,10,-58,-87,-27,-25,-57,21, 
  /* [22][0][][] */ 47,1,-20,23,15,8,13,-26,-10,7,55,15,-10, 91,16,-11,-26,2,1,7,20,-13,-29,-27,18,13, -127,-13,7,-15,-29,-9,-21,23,64,31,-4,-16,-22, 
  /* [23][0][][] */ 52,-83,127,-52,-23,-33,-18,-71,38,-44,-33,49,60, -72,-101,38,-92,-8,16,14,59,47,35,-46,-35,-34, -93,-96,4,-4,56,-2,-92,-64,-48,-15,-51,-6,22, 
  /* [24][0][][] */ 38,66,-16,-57,-89,-64,-49,-28,21,41,-9,5,29, 58,92,53,21,67,21,-77,-26,-2,3,-28,-19,-16, -37,-127,24,101,61,17,-20,-21,-38,9,86,37,-13, 
  /* [25][0][][] */ 71,127,-89,-79,-7,42,-41,-47,85,0,14,85,-54, 53,33,18,-28,-29,3,-38,74,69,30,46,-47,56, -39,89,105,71,-5,-69,-41,19,108,63,56,-83,48, 
  /* [26][0][][] */ -25,-10,-53,57,23,-39,-9,30,9,-55,-38,-43,-42, 45,91,15,36,78,55,52,64,44,-70,-45,-96,27, -127,4,-38,-12,3,45,60,19,-39,-16,-57,10,8, 
  /* [27][0][][] */ -127,-25,-64,-63,-46,14,16,17,44,-9,-10,-26,20, 14,12,64,68,47,-50,-74,-41,-40,-43,41,58,21, 106,-27,19,-37,-45,16,38,33,2,9,-14,-12,4, 
  /* [28][0][][] */ 127,3,34,5,-47,-21,-34,-21,-16,27,7,15,8, 5,-46,61,-40,12,27,-14,-33,8,25,-6,-21,-24, -43,-66,43,-61,5,-14,-37,-20,-27,-11,-9,22,-22, 
  /* [29][0][][] */ 60,99,127,40,80,-8,34,23,21,6,-16,6,35, 58,75,76,56,12,28,15,22,35,-46,58,-2,-12, 62,64,9,74,-52,72,-56,50,14,-29,15,26,-43, 
  /* [30][0][][] */ 38,5,-36,28,5,20,10,14,9,-3,0,13,25, -97,7,-54,24,60,5,11,-6,-6,9,-11,-43,8, -127,-53,-28,10,22,32,9,7,-50,-42,-11,-8,7, 
  /* [31][0][][] */ -55,2,-32,-59,-8,-2,-19,-32,-26,-15,1,24,-16, -127,-4,41,54,46,38,-3,13,38,2,18,14,-24, -23,44,-7,-2,-9,-6,15,7,45,18,29,1,3, 
};
const TfArray<4, int> tensor_dimension15 = { 4, { 32,1,3,13 } };
const TfArray<32, float> quant15_scale = { 32, { 0.0043618869967758656, 0.0038754502311348915, 0.0049482248723506927, 0.0037519026082009077, 0.0037008863873779774, 0.0031437692232429981, 0.0068632918410003185, 0.0050172414630651474, 0.0052967951633036137, 0.0056338994763791561, 0.0056434706784784794, 0.0046490398235619068, 0.0066786170937120914, 0.0046022068709135056, 0.0043362947180867195, 0.0046888752840459347, 0.0041830060072243214, 0.0049139205366373062, 0.008357086218893528, 0.0037419602740556002, 0.0037987544201314449, 0.0037882814649492502, 0.0085398498922586441, 0.0042337537743151188, 0.004659382626414299, 0.0035132493358105421, 0.0048257014714181423, 0.0059342472814023495, 0.0066232685931026936, 0.0035245702601969242, 0.0068223285488784313, 0.0076259183697402477, } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&g0::quant14_zero, 0 };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,13 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,32 } };
const TfArray<1, float> quant17_scale = { 1, { 0.034239891916513443, } };
const TfArray<1, int> quant17_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&quant17_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,32 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,32 } };
const TfArray<4, int> tensor_dimension20 = { 4, { 1,1,25,32 } };
const TfArray<4, int> tensor_dimension21 = { 4, { 1,1,25,16 } };
const TfArray<1, float> quant21_scale = { 1, { 0.049153100699186325, } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&g0::quant17_zero, 0 };
const TfArray<4, int> tensor_dimension22 = { 4, { 1,25,1,16 } };
const TfArray<4, int> tensor_dimension23 = { 4, { 1,13,1,16 } };
const TfArray<4, int> tensor_dimension24 = { 4, { 1,1,13,16 } };
const TfArray<4, int> tensor_dimension25 = { 4, { 1,1,13,8 } };
const TfArray<1, float> quant25_scale = { 1, { 0.044562708586454391, } };
const TfLiteAffineQuantization quant25 = { (TfLiteFloatArray*)&quant25_scale, (TfLiteIntArray*)&g0::quant17_zero, 0 };
const TfArray<4, int> tensor_dimension26 = { 4, { 1,13,1,8 } };
const TfArray<4, int> tensor_dimension27 = { 4, { 1,7,1,8 } };
const TfArray<2, int> tensor_dimension28 = { 2, { 1,56 } };
const TfArray<2, int> tensor_dimension29 = { 2, { 1,6 } };
const TfArray<1, float> quant29_scale = { 1, { 0.24223212897777557, } };
const TfArray<1, int> quant29_zero = { 1, { 62 } };
const TfLiteAffineQuantization quant29 = { (TfLiteFloatArray*)&quant29_scale, (TfLiteIntArray*)&quant29_zero, 0 };
const TfArray<1, float> quant30_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant30 = { (TfLiteFloatArray*)&quant30_scale, (TfLiteIntArray*)&g0::quant17_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 16 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 16,15,14 } };
const TfArray<1, int> outputs1 = { 1, { 17 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 17,2 } };
const TfArray<1, int> outputs2 = { 1, { 18 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 18 } };
const TfArray<1, int> outputs3 = { 1, { 19 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 19,3 } };
const TfArray<1, int> outputs4 = { 1, { 20 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 20,13,12 } };
const TfArray<1, int> outputs5 = { 1, { 21 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 21,4 } };
const TfArray<1, int> outputs6 = { 1, { 22 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 22 } };
const TfArray<1, int> outputs7 = { 1, { 23 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 23,5 } };
const TfArray<1, int> outputs8 = { 1, { 24 } };
const TfLiteConvParams opdata9 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs9 = { 3, { 24,11,10 } };
const TfArray<1, int> outputs9 = { 1, { 25 } };
const TfLiteReshapeParams opdata10 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs10 = { 2, { 25,6 } };
const TfArray<1, int> outputs10 = { 1, { 26 } };
const TfLitePoolParams opdata11 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs11 = { 1, { 26 } };
const TfArray<1, int> outputs11 = { 1, { 27 } };
const TfLiteReshapeParams opdata12 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs12 = { 2, { 27,7 } };
const TfArray<1, int> outputs12 = { 1, { 28 } };
const TfLiteFullyConnectedParams opdata13 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs13 = { 3, { 28,9,8 } };
const TfArray<1, int> outputs13 = { 1, { 29 } };
const TfLiteSoftmaxParams opdata14 = { 1 };
const TfArray<1, int> inputs14 = { 1, { 29 } };
const TfArray<1, int> outputs14 = { 1, { 30 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 656), (TfLiteIntArray*)&g0::tensor_dimension0, 650, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 336, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data12, (TfLiteIntArray*)&g0::tensor_dimension12, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data13, (TfLiteIntArray*)&g0::tensor_dimension13, 1536, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data14, (TfLiteIntArray*)&g0::tensor_dimension14, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data15, (TfLiteIntArray*)&g0::tensor_dimension15, 1248, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 650, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 1600), (TfLiteIntArray*)&g0::tensor_dimension17, 1600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 1600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 1600), (TfLiteIntArray*)&g0::tensor_dimension19, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension21, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension22, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension23, 208, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension24, 208, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension25, 104, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension26, 104, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 112), (TfLiteIntArray*)&g0::tensor_dimension27, 56, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension28, 56, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension29, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant29))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension29, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant30))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[15] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs13, (TfLiteIntArray*)&g0::outputs13, (TfLiteIntArray*)&g0::inputs13, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata13)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs14, (TfLiteIntArray*)&g0::outputs14, (TfLiteIntArray*)&g0::inputs14, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata14)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[15] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs13, (TfLiteIntArray*)&g0::outputs13, (TfLiteIntArray*)&g0::inputs13, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata13)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs14, (TfLiteIntArray*)&g0::outputs14, (TfLiteIntArray*)&g0::inputs14, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata14)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 31, };
const size_t tflNodes_subgraph_index[] = {0, 15, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  30, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_923005_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 31;
  for (size_t i = 0; i < 31; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_923005_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_923005_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_923005_3_invoke() {
  for (size_t i = 0; i < 15; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_923005_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
